steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ekg-agent:$SHORT_SHA', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ekg-agent:$SHORT_SHA']
  
  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/ekg-agent:$SHORT_SHA', 'gcr.io/$PROJECT_ID/ekg-agent:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ekg-agent:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ekg-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ekg-agent:$SHORT_SHA'
      - '--region'
      - 'europe-west6'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,SESSION_SECRET_KEY=session-secret-key:latest'
      - '--set-env-vars'
      - 'LOG_LEVEL=INFO,CACHE_DIR=/tmp/ekg_cache,MAX_CACHE_SIZE=1000,CACHE_TTL=3600,WEALTH_MANAGEMENT_KG_PATH=gs://YOUR_BUCKET/kg/wealth_product_kg.json,APF_KG_PATH=gs://YOUR_BUCKET/kg/apf_kg.json'

images:
  - 'gcr.io/$PROJECT_ID/ekg-agent:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ekg-agent:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

